### ISSUE TITLE
version 0 milestone

### ISSUE THREAD

**Issue by zeakd** [zeakd/tinypost#1]
- [ ] readme
  - [ ] cli usage
  - [ ] API
  - [ ] configurations
  - [ ] file path resolve
  - [ ] middlewares
- [ ] renderer option enhance
- [ ] layout
  - [ ] default 
  - [ ] js layout
- [ ] merge `config` with user flags.
- [ ] watch files
- [ ] use babel
  - for ava
  - for async await

**Comment by zeakd** [comment]
# 안녕
